# Cloud Build configuration for deploying to Cloud Run
# Usage: gcloud builds submit --config=cloudbuild.yaml

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:$BUILD_ID'
      - '-t'
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: '1200s'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-wagnersilva-eu'
      - '--image'
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:$BUILD_ID'
      - '--region'
      - 'europe-north2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'GOOGLE_GENERATIVE_AI_API_KEY=GOOGLE_GENERATIVE_AI_API_KEY:latest,HUGGING_FACE_HUB_TOKEN=HUGGING_FACE_HUB_TOKEN:latest'

# Images to be pushed to Artifact Registry
images:
  - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:$BUILD_ID'
  - 'europe-north2-docker.pkg.dev/$PROJECT_ID/docker/portfolio-wagnersilva-eu:latest'

# Build timeout
timeout: '2400s'

# Machine type for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
